{% set name = "cleanco" %}
{% set version = "2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cleanco-{{ version }}.tar.gz
  sha256: 26b899b2be871be288408205686c5a1dd5f3ab085b709d041a77f3e3049d2961

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - cleanco
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/psolin/cleanco
  summary: Python library to process company names
  license: MIT
  # License file manually packaged. See https://github.com/psolin/cleanco/pull/74
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - izahn
